### ISSUE TITLE
[Question] SD Card Reader

### ISSUE THREAD

**Issue by arvedviehweger** [matthew728960/Clover-ACER-E1-471G#1]
Hi,

I saw you got the Sd card reader working with Mac OS X on this Laptop using a DSDT Patch.

My question is, what kind of card reader is built-into the Chromebook? Is it PCIE or Usb based?

If it is PCIE based, which patch did you apply?

Thank you very much.

**Comment by Ardentwheel** [comment]
I'm using kext from [this site](http://www.insanelymac.com/forum/topic/321080-sineteks-driver-for-realtek-rtsx-sdhc-card-readers/).
