### ISSUE TITLE
Can it driver AR946x in Serria

### ISSUE THREAD

**Issue by korira** [matthew728960/Clover-ACER-E1-471G#2]
I download the driver to patch kext for wifi, and delete the original driver, reboot my computer, I found the kext can't working in Mac OS Serria, could update again?

**Comment by Ardentwheel** [comment]
There are [10.12](https://github.com/matthew728960/Clover-ACER-E1-471G/blob/master/Tools/AR5B22/AirPortAtheros40-AR946X.v5.kext-10.12.x.zip) version available.
