### ISSUE TITLE
wifi kext stopped working after updating to 10.13

### ISSUE THREAD

**Issue by mah-qurashy** [matthew728960/Clover-ACER-E1-471G#6]
i have an ar9462 on asus laptop and wifi was working on sierra using AirPortAtheros40-AR9462-patch16
after directly updating to high sierra from app store, it shows No hardware installed in wifi menu

**Comment by mertcdev** [comment]
http://www.insanelymac.com/forum/topic/312045-atheros-wireless-driver-os-x-101112-for-unsupported-cards/page-20#entry2503465

**Comment by mah-qurashy** [comment]
thank you. wifi works now but no bluetooth

**Comment by mertcdev** [comment]
Install IO80211Family.kext System/Library/Extensions https://drive.google.com/file/d/0B13iVEnkfsRXdjNkVkJWUmdtLVE/view?usp=sharing
