### ISSUE TITLE
DSDT-Patch/Fix_EC0.txt

### ISSUE THREAD

**Issue by likinmutakin** [matthew728960/Clover-ACER-E1-471G#7]
need help...please explain function of DSDT-Patch/Fix_EC0.txt?
Clover-ACER-E1-471G/Tools/DSDT-Patch/Fix_EC0.txt
thanks in advance.
i also use SmartTouchPad for my acer....

**Comment by Ardentwheel** [comment]
DSDT-Patch folder just records the DSDT patch used in DSDT. Just use the EFI folder, other is not necessary.
